language: objective-c
osx_image: xcode7.1
xcode_sdk: iphonesimulator9.0

before_install:
  - gem install xcpretty --no-document
script:
  - xcodebuild -project TreeSet.xcodeproj -scheme TreeSet -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' test | xcpretty -c
